-- CreateTable
CREATE TABLE `PerformanceRecord` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `orderId` INTEGER NOT NULL,
    `dispatchId` INTEGER NULL,
    `settlementId` INTEGER NULL,
    `ownerUserId` INTEGER NOT NULL,
    `ownerRoleType` ENUM('PLAYER', 'CS', 'OPERATION', 'CHANNEL', 'LEADER') NOT NULL,
    `statsDate` DATE NOT NULL,
    `statsMonth` VARCHAR(7) NOT NULL,
    `billingMode` ENUM('HOURLY', 'GUARANTEED', 'MODE_PLAY') NULL,
    `orderType` ENUM('EXPERIENCE', 'FUN', 'ESCORT', 'LUCKY_BAG', 'BLIND_BOX', 'CUSTOM', 'CUSTOMIZED') NULL,
    `projectId` INTEGER NULL,
    `bizLine` VARCHAR(50) NULL,
    `grossPerformanceAmount` DECIMAL(12, 2) NOT NULL,
    `netIncomeAmount` DECIMAL(12, 2) NOT NULL,
    `negativeIncomeAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `contributionBaseAmount` DECIMAL(12, 2) NULL,
    `commissionRate` DECIMAL(6, 4) NULL,
    `isAccepted` BOOLEAN NOT NULL DEFAULT false,
    `isArchived` BOOLEAN NOT NULL DEFAULT false,
    `isCompleted` BOOLEAN NOT NULL DEFAULT false,
    `isBombed` BOOLEAN NOT NULL DEFAULT false,
    `isComplained` BOOLEAN NOT NULL DEFAULT false,
    `isAfterSale` BOOLEAN NOT NULL DEFAULT false,
    `isCancelled` BOOLEAN NOT NULL DEFAULT false,
    `complaintOrderAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `complaintPenaltyAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `remark` VARCHAR(255) NULL,
    `status` ENUM('EFFECTIVE', 'REVOKED') NOT NULL DEFAULT 'EFFECTIVE',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `idx_perf_owner_date`(`ownerUserId`, `ownerRoleType`, `statsDate`),
    INDEX `idx_perf_role_date`(`ownerRoleType`, `statsDate`),
    INDEX `idx_perf_order`(`orderId`),
    INDEX `idx_perf_dispatch`(`dispatchId`),
    INDEX `idx_perf_settlement`(`settlementId`),
    INDEX `idx_perf_billing_date`(`billingMode`, `statsDate`),
    INDEX `idx_perf_ordertype_date`(`orderType`, `statsDate`),
    INDEX `idx_perf_project_date`(`projectId`, `statsDate`),
    INDEX `idx_perf_bizline_date`(`bizLine`, `statsDate`),
    INDEX `idx_perf_bombed_date`(`isBombed`, `statsDate`),
    INDEX `idx_perf_complained_date`(`isComplained`, `statsDate`),
    INDEX `idx_perf_aftersale_date`(`isAfterSale`, `statsDate`),
    INDEX `idx_perf_cancelled_date`(`isCancelled`, `statsDate`),
    INDEX `idx_perf_stats_month`(`statsMonth`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OrderFinanceRecord` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `orderId` INTEGER NOT NULL,
    `customerUserId` INTEGER NULL,
    `statsDate` DATE NOT NULL,
    `statsMonth` VARCHAR(7) NOT NULL,
    `billingMode` ENUM('HOURLY', 'GUARANTEED', 'MODE_PLAY') NULL,
    `orderType` ENUM('EXPERIENCE', 'FUN', 'ESCORT', 'LUCKY_BAG', 'BLIND_BOX', 'CUSTOM', 'CUSTOMIZED') NULL,
    `projectId` INTEGER NULL,
    `bizLine` VARCHAR(50) NULL,
    `receivableAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `paidAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `discountAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `couponDiscountAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `otherDiscountAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `playerCostAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `csCostAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `operationCostAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `channelCostAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `complaintPenaltyAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `afterSaleCostAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `grossProfitAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `isComplained` BOOLEAN NOT NULL DEFAULT false,
    `isAfterSale` BOOLEAN NOT NULL DEFAULT false,
    `isCancelled` BOOLEAN NOT NULL DEFAULT false,
    `remark` VARCHAR(255) NULL,
    `status` ENUM('EFFECTIVE', 'VOIDED') NOT NULL DEFAULT 'EFFECTIVE',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `OrderFinanceRecord_orderId_key`(`orderId`),
    INDEX `idx_fin_stats_date`(`statsDate`),
    INDEX `idx_fin_stats_month`(`statsMonth`),
    INDEX `idx_fin_customer_date`(`customerUserId`, `statsDate`),
    INDEX `idx_fin_billing_date`(`billingMode`, `statsDate`),
    INDEX `idx_fin_ordertype_date`(`orderType`, `statsDate`),
    INDEX `idx_fin_project_date`(`projectId`, `statsDate`),
    INDEX `idx_fin_bizline_date`(`bizLine`, `statsDate`),
    INDEX `idx_fin_complained_date`(`isComplained`, `statsDate`),
    INDEX `idx_fin_aftersale_date`(`isAfterSale`, `statsDate`),
    INDEX `idx_fin_cancelled_date`(`isCancelled`, `statsDate`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
