CREATE TABLE `complaint_work_orders` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `ticketNo` VARCHAR(64) NOT NULL,
  `orderId` INTEGER NOT NULL,
  `userId` INTEGER NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `reason` VARCHAR(120) NOT NULL,
  `description` TEXT NULL,
  `paymentChannel` VARCHAR(32) NULL,
  `refundSupported` BOOLEAN NOT NULL DEFAULT false,
  `refundUnsupportedReason` VARCHAR(255) NULL,
  `suggestedRefundAmount` DECIMAL(10, 2) NULL,
  `approvedRefundAmount` DECIMAL(10, 2) NULL,
  `reviewRemark` VARCHAR(255) NULL,
  `refundRemark` VARCHAR(255) NULL,
  `reviewedBy` INTEGER NULL,
  `reviewedAt` DATETIME(3) NULL,
  `refundedBy` INTEGER NULL,
  `refundedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `complaint_work_orders_ticketNo_key`(`ticketNo`),
  UNIQUE INDEX `complaint_work_orders_orderId_key`(`orderId`),
  INDEX `idx_complaint_work_orders_status_time`(`status`, `createdAt`),
  INDEX `idx_complaint_work_orders_user_time`(`userId`, `createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
