-- AlterTable
ALTER TABLE `wallet_transactions` MODIFY `bizType` ENUM('SETTLEMENT_EARNING', 'SETTLEMENT_EARNING_BASE', 'SETTLEMENT_EARNING_CARRY', 'SETTLEMENT_BOMB_LOSS', 'SETTLEMENT_EARNING_CS', 'RELEASE_FROZEN', 'REFUND_REVERSAL', 'WITHDRAW_RESERVE', 'WITHDRAW_RELEASE', 'WITHDRAW_PAYOUT') NOT NULL;
