ALTER TABLE `users`
  ADD COLUMN `activityAssessmentEnabled` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `activityAssessmentStartedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  ADD COLUMN `activityLastCompletedAt` DATETIME(3) NULL,
  ADD COLUMN `activityNextChargeAt` DATETIME(3) NULL,
  ADD COLUMN `activityTimerPaused` BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE `wallet_transactions`
  MODIFY COLUMN `bizType` ENUM('SETTLEMENT_EARNING','SETTLEMENT_EARNING_BASE','SETTLEMENT_EARNING_CARRY','SETTLEMENT_EARNING_CS','SETTLEMENT_BOMB_LOSS','ORDER_RENEWAL_BONUS','ORDER_RENEWAL_BONUS_REVERSAL','RELEASE_FROZEN','REFUND_REVERSAL','WITHDRAW_RESERVE','WITHDRAW_RELEASE','WITHDRAW_PAYOUT','DEPOSIT_REFUND','DEPOSIT_ADD','DEPOSIT_DEDUCT','OFFLINE_FEE_PAYMENT','EQUIPMENT_RENTAL_FEE','RENTAL_ORDER_PREPAY','RENTAL_ORDER_DEPOSIT','RENTAL_ORDER_REFUND','RENTAL_ORDER_EXCESS_CHARGE','RENTAL_ORDER_VOID_REFUND','SETTLEMENT_REVERSAL','SETTLEMENT_RECALC','MEMBER_RECHARGE','MEMBER_RECHARGE_BONUS','MEMBER_ORDER_CONSUME','MEMBER_RECHARGE_REFUND','STAFF_EXIT_RELEASE','STAFF_EXIT_CLEAR','STAFF_ACTIVITY_PENALTY') NOT NULL;

ALTER TABLE `wallet_deposit_transactions`
  MODIFY COLUMN `bizType` ENUM('WITHDRAW_PERCENT','REWARD_TRANSFER','MANUAL_DEPOSIT','PENALTY_DEDUCT','DEPOSIT_REFUND','STAFF_EXIT_RELEASE','STAFF_EXIT_CLEAR','ACTIVITY_PENALTY') NOT NULL;

ALTER TABLE `penalty_fund_flows`
  MODIFY COLUMN `bizType` ENUM('PENALTY_DEDUCT','APPEAL_REFUND','MANUAL_ADJUST','ACTIVITY_DEDUCT') NOT NULL;

CREATE TABLE `staff_leaves` (
  `id` INTEGER NOT NULL AUTO_INCREMENT, `userId` INTEGER NOT NULL, `days` INTEGER NOT NULL,
  `startAt` DATETIME(3) NOT NULL, `endAt` DATETIME(3) NOT NULL, `actualEndAt` DATETIME(3) NULL,
  `status` ENUM('SCHEDULED','ACTIVE','COMPLETED','EARLY_ENDED','CANCELED') NOT NULL DEFAULT 'SCHEDULED',
  `reason` VARCHAR(255) NULL, `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL,
  INDEX `idx_staff_leave_user_status_time` (`userId`,`status`,`startAt`,`endAt`), INDEX `idx_staff_leave_status_time` (`status`,`startAt`,`endAt`),
  PRIMARY KEY (`id`), CONSTRAINT `staff_leaves_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `staff_activity_charges` (
  `id` INTEGER NOT NULL AUTO_INCREMENT, `userId` INTEGER NOT NULL, `scheduledAt` DATETIME(3) NOT NULL,
  `inactivityHours` INTEGER NOT NULL, `rateTier` INTEGER NOT NULL, `expectedAmount` DECIMAL(10,2) NOT NULL,
  `availableDeducted` DECIMAL(10,2) NOT NULL DEFAULT 0, `depositDeducted` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `walletTxId` INTEGER NULL, `depositTxId` INTEGER NULL, `exitTriggered` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `uniq_staff_activity_charge_schedule` (`userId`,`scheduledAt`), INDEX `idx_staff_activity_charge_created` (`createdAt`), INDEX `idx_staff_activity_charge_exit` (`exitTriggered`,`createdAt`),
  PRIMARY KEY (`id`), CONSTRAINT `staff_activity_charges_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
