-- AlterTable
ALTER TABLE `Order` MODIFY `status` ENUM('WAIT_ASSIGN', 'WAIT_ACCEPT', 'ACCEPTED', 'ARCHIVED', 'COMPLETED_PENDING_CONFIRM', 'COMPLETED', 'WAIT_REVIEW', 'REVIEWED', 'WAIT_AFTERSALE', 'AFTERSALE_DONE', 'REFUNDED') NOT NULL DEFAULT 'WAIT_ASSIGN';
